# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ad1b9a93de9c521f99a3d48219794e409927b9f1e2ae8ef05e18ea67396fa63089e0ba5ec8f929cddc3d86e54176615f721bc84a097789dfcea80e0f9422ea9

test:
  secret_key_base: a90d0a5af287735344b9787417cf91ec7fa5495e46623a686e47d678c96aef014194fc02c52127197b08789c5918c4c4eaa715d74b142c446bb1bba1d0192aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
